from .debtSerializer import *
from .departmentSerializer import *
from .employeeSerializer import *
from .obervationsSerializer import *
from .smallBoxSerializer import *
from .registerRHSerializer import *
from .foodSerializer import *
from .commentSerializer import *
from .perceptionSerializer import *
from .deductionSerializer import *
from .vacationSerializer import *
from .payrollSerializer import *