# Generated by Django 4.1.1 on 2022-09-28 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemafcApp', '0004_employee_iscurrent_alter_employee_enddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
