# Generated by Django 4.1.1 on 2022-09-30 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistemafcApp', '0006_employee_isactive'),

    ]

    operations = [
        migrations.CreateModel(
            name='RegisterRH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromDate', models.TextField(max_length=50)),
                ('toDate', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='smallbox',
            name='employee',
        ),
        migrations.CreateModel(
            name='RegisterDetailRH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuality', models.BooleanField(default=True)),
                ('attendance', models.BooleanField(default=True)),
                ('abscense', models.IntegerField(default=0)),
                ('overtimeMinutes', models.IntegerField(default=0)),
                ('lu', models.CharField(choices=[('Asistencia', 'Asistencia'), ('Doblada', 'Doblada'), ('Falta justificada', 'Falta Justificada'), ('Falta injustificada', 'Falta Injustificada'), ('Descanso', 'Descanso')], default='Asistencia', max_length=25)),
                ('ma', models.CharField(choices=[('Asistencia', 'Asistencia'), ('Doblada', 'Doblada'), ('Falta justificada', 'Falta Justificada'), ('Falta injustificada', 'Falta Injustificada'), ('Descanso', 'Descanso')], default='Asistencia', max_length=25)),
                ('mi', models.CharField(choices=[('Asistencia', 'Asistencia'), ('Doblada', 'Doblada'), ('Falta justificada', 'Falta Justificada'), ('Falta injustificada', 'Falta Injustificada'), ('Descanso', 'Descanso')], default='Asistencia', max_length=25)),
                ('ju', models.CharField(choices=[('Asistencia', 'Asistencia'), ('Doblada', 'Doblada'), ('Falta justificada', 'Falta Justificada'), ('Falta injustificada', 'Falta Injustificada'), ('Descanso', 'Descanso')], default='Asistencia', max_length=25)),
                ('vi', models.CharField(choices=[('Asistencia', 'Asistencia'), ('Doblada', 'Doblada'), ('Falta justificada', 'Falta Justificada'), ('Falta injustificada', 'Falta Injustificada'), ('Descanso', 'Descanso')], default='Asistencia', max_length=25)),
                ('sa', models.CharField(choices=[('Asistencia', 'Asistencia'), ('Doblada', 'Doblada'), ('Falta justificada', 'Falta Justificada'), ('Falta injustificada', 'Falta Injustificada'), ('Descanso', 'Descanso')], default='Asistencia', max_length=25)),
                ('do', models.CharField(choices=[('Asistencia', 'Asistencia'), ('Doblada', 'Doblada'), ('Falta justificada', 'Falta Justificada'), ('Falta injustificada', 'Falta Injustificada'), ('Descanso', 'Descanso')], default='Descanso', max_length=25)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sistemafcApp.employee', unique=True)),
            ],
        ),
    ]
