# Generated by Django 4.1.1 on 2022-09-30 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistemafcApp', '0007_registerrh_remove_smallbox_employee_registerdetailrh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smallbox',
            name='registerDetail',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.RESTRICT, to='sistemafcApp.registerdetailrh'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registerrh',
            name='toDate',
            field=models.TextField(default='12/12/1997', max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lu', models.BooleanField(default=True)),
                ('ma', models.BooleanField(default=True)),
                ('mi', models.BooleanField(default=True)),
                ('ju', models.BooleanField(default=True)),
                ('vi', models.BooleanField(default=True)),
                ('registerDetail', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sistemafcApp.registerdetailrh')),
            ],
        ),
    ]
