# Generated by Django 4.1.1 on 2022-09-30 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistemafcApp', '0008_smallbox_registerdetail_alter_registerrh_todate_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerdetailrh',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sistemafcApp.employee'),
        ),
    ]
