# Generated by Django 4.1.1 on 2022-09-30 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistemafcApp', '0010_registerdetailrh_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerdetailrh',
            name='register',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='registerdetailrh_set', to='sistemafcApp.registerrh'),
        ),
    ]
