# Generated by Django 4.1.1 on 2022-09-30 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistemafcApp', '0011_alter_registerdetailrh_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='registerDetail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='food_set', to='sistemafcApp.registerdetailrh'),
        ),
        migrations.AlterField(
            model_name='smallbox',
            name='registerDetail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='smallbox_set', to='sistemafcApp.registerdetailrh'),
        ),
    ]
