# Generated by Django 4.1.1 on 2022-09-30 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistemafcApp', '0012_alter_food_registerdetail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registerdetailrh',
            old_name='register',
            new_name='registerRH',
        ),
    ]
