# Generated by Django 4.1.1 on 2022-09-30 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistemafcApp', '0013_rename_register_registerdetailrh_registerrh'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registerdetailrh',
            old_name='registerRH',
            new_name='register',
        ),
    ]
