# Generated by Django 4.1.1 on 2022-10-03 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistemafcApp', '0015_alter_registerdetailrh_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='registerDetail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='food_set', to='sistemafcApp.registerdetailrh', unique=True),
        ),
    ]
