# Generated by Django 4.1.1 on 2022-10-03 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistemafcApp', '0016_alter_food_registerdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='registerDetail',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='food_set', to='sistemafcApp.registerdetailrh'),
        ),
    ]
