# Generated by Django 4.1.1 on 2022-10-03 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistemafcApp', '0017_alter_food_registerdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='registerDetail',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='food_set', to='sistemafcApp.registerdetailrh'),
        ),
        migrations.AlterField(
            model_name='registerdetailrh',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_set', to='sistemafcApp.employee'),
        ),
        migrations.AlterField(
            model_name='registerdetailrh',
            name='register',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registerdetailrh_set', to='sistemafcApp.registerrh'),
        ),
        migrations.AlterField(
            model_name='smallbox',
            name='registerDetail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smallbox_set', to='sistemafcApp.registerdetailrh'),
        ),
    ]
