# Generated by Django 4.1.1 on 2022-10-03 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistemafcApp', '0018_alter_food_registerdetail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observations',
            name='employee',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='observations_set', to='sistemafcApp.employee'),
            preserve_default=False,
        ),
    ]
