# Generated by Django 4.1.1 on 2022-10-03 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistemafcApp', '0019_observations_employee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Observations',
            new_name='Observation',
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500)),
                ('date', models.TextField(max_length=50)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_set', to='sistemafcApp.registerdetailrh')),
            ],
        ),
    ]
