# Generated by Django 4.1.1 on 2022-10-03 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistemafcApp', '0020_rename_observations_observation_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='employee',
            new_name='registerDetail',
        ),
    ]
