# Generated by Django 4.1.1 on 2022-10-03 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistemafcApp', '0021_rename_employee_comment_registerdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smallbox',
            old_name='note',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='smallbox',
            name='name',
        ),
    ]
