# Generated by Django 4.1.1 on 2022-10-04 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemafcApp', '0022_rename_note_smallbox_comment_remove_smallbox_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smallbox',
            name='comment',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
