# Generated by Django 4.1.1 on 2022-10-04 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistemafcApp', '0023_alter_smallbox_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeductionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PerceptionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Perception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(blank=True, default=0, null=True)),
                ('note', models.TextField(max_length=500)),
                ('creationDate', models.TextField(max_length=50)),
                ('percentual', models.BooleanField(default=False)),
                ('isActive', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sistemafcApp.employee')),
                ('type', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='sistemafcApp.perceptiontype')),
            ],
        ),
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(blank=True, default=0, null=True)),
                ('note', models.TextField(max_length=500)),
                ('creationDate', models.TextField(max_length=50)),
                ('toPayNow', models.BooleanField(default=True)),
                ('payed', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sistemafcApp.employee')),
                ('type', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='sistemafcApp.deductiontype')),
            ],
        ),
    ]
