# Generated by Django 4.1.1 on 2022-10-05 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistemafcApp', '0025_alter_perception_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deduction',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='employee_deduction_set', to='sistemafcApp.employee'),
        ),
    ]
