# Generated by Django 4.1.1 on 2022-10-05 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistemafcApp', '0026_alter_deduction_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deduction',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sistemafcApp.deductiontype'),
        ),
        migrations.AlterField(
            model_name='perception',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sistemafcApp.perceptiontype'),
        ),
    ]
