# Generated by Django 4.1.1 on 2022-10-06 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistemafcApp', '0027_alter_deduction_type_alter_perception_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.IntegerField(blank=True, default=0, null=True)),
                ('note', models.TextField(max_length=500)),
                ('fromDate', models.TextField(max_length=50)),
                ('toDate', models.TextField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='employee_vacation_set', to='sistemafcApp.employee')),
            ],
        ),
    ]
