# Generated by Django 4.1.1 on 2022-10-09 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistemafcApp', '0029_perception_isforsalary_alter_vacation_todate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inflationPercentage', models.FloatField(default=7.0)),
                ('extraHourPrice', models.FloatField(default=50.0)),
                ('registerRH', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sistemafcApp.employee')),
            ],
        ),
        migrations.CreateModel(
            name='RegisterPayroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perceptionsAmount', models.FloatField(default=0)),
                ('deductionsAmount', models.FloatField(default=0)),
                ('cardAmount', models.FloatField(default=0)),
                ('attendanceAmount', models.FloatField(default=0)),
                ('salaryAmount', models.FloatField(default=0)),
                ('infonavitAmount', models.FloatField(default=0)),
                ('vacationsAmount', models.FloatField(default=0)),
                ('settlementAmount', models.FloatField(default=0)),
                ('overtimeAmount', models.FloatField(default=0)),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='payrolldetail_set', to='sistemafcApp.payroll')),
                ('registerDetail', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='registerdetail_set', to='sistemafcApp.employee')),
            ],
        ),
    ]
