# Generated by Django 4.1.1 on 2022-10-09 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistemafcApp', '0030_payroll_registerpayroll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='registerRH',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sistemafcApp.registerrh'),
        ),
    ]
