# Generated by Django 4.1.1 on 2022-11-11 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistemafcApp', '0033_employee_attendanceprice_employee_extrahourprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='registerRH',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='registerrh_set', to='sistemafcApp.registerrh'),
        ),
    ]
