# Generated by Django 4.1.1 on 2022-11-14 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistemafcApp', '0034_alter_payroll_registerrh'),
    ]

    operations = [
        migrations.AddField(
            model_name='smallbox',
            name='isSplitted',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SmallBoxSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(blank=True, default=0, null=True)),
                ('isPayed', models.BooleanField(default=False)),
                ('payedDate', models.TextField(blank=True, max_length=50, null=True)),
                ('smallBoxRegister', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemafcApp.smallbox')),
            ],
        ),
    ]
