# Generated by Django 4.1.1 on 2022-11-14 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistemafcApp', '0035_smallbox_issplitted_smallboxsplit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smallboxsplit',
            name='smallBoxRegister',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smallboxsplit_set', to='sistemafcApp.smallbox'),
        ),
    ]
