# Generated by Django 4.1.1 on 2022-12-18 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistemafcApp', '0036_alter_smallboxsplit_smallboxregister'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smallbox',
            name='isSplitted',
        ),
    ]
