//SITEMAFC
export const SET_SEARCH_REGISTER_RH = "SET_SEARCH_REGISTER_RH";
export const SHOW_NEW_EMPLOYEE_OVERLAY = "SHOW_NEW_EMPLOYEE_OVERLAY";

//Auth
export const SIGNIN = "SIGNIN";


//Rh
export const SET_SELECTED_REGISTER_RH = "SET_SELECTED_REGISTER_RH";
export const SET_SELECTED_REGISTER_ID = "SET_SELECTED_REGISTER_ID";
export const FETCH_EMPLOYEE_LIST = "FETCH_EMPLOYEE_LIST";
export const FETCH_DEPARTMENT_LIST = "FETCH_DEPARTMENT_LIST";
export const FETCH_EMPLOYEE_FOR_REGISTER_LIST = "FETCH_EMPLOYEE_FOR_REGISTER_LIST";
export const SET_REGISTERS = "SET_REGISTERS";
export const ADD_SMALLBOX_REGISTER = "ADD_SMALLBOX_REGISTER";
export const INITIALIZE_REGISTER = "INITIALIZE_REGISTER";
export const SET_REGISTERS_DETAILS = "SET_REGISTERS_DETAILS";
export const SAVE_REGISTER = "SAVE_REGISTER";
export const FETCH_REGISTERS = "FETCH_REGISTERS";
export const SELECTED_REGISTER_DETAIL = "SELECTED_REGISTER_DETAIL";
export const CLEAR_NEW_REGISTER = "CLEAR_NEW_REGISTER";
export const SET_SELECTED_REGISTER = "SET_SELECTED_REGISTER";
export const SET_SELECTED_REGISTERS_DETAILS = "SET_SELECTED_REGISTERS_DETAILS";

