//SITEMAFC
export const SET_SEARCH_REGISTER_RH = "SET_SEARCH_REGISTER_RH";
export const SHOW_NEW_EMPLOYEE_OVERLAY = "SHOW_NEW_EMPLOYEE_OVERLAY";

//Auth
export const SIGNIN = "SIGNIN";

//Employees
export const SHOW_NEW_EMPLOYEE_FULL_OVERLAY = "SHOW_NEW_EMPLOYEE_FULL_OVERLAY";
export const SET_SEARCH_EMPLOYEE = "SET_SEARCH_EMPLOYEE";
export const SET_SEARCH_EMPLOYEE_FULL = "SET_SEARCH_EMPLOYEE_FULL";
export const SET_DEPARTMENT_FULL_LIST = "SET_DEPARTMENT_FULL_LIST";

//Vacations
export const SHOW_NEW_VACATION_OVERLAY = "SHOW_NEW_VACATION_OVERLAY";
export const SET_EMPLOYEE_VACATIONS_LIST = "SET_EMPLOYEE_VACATIONS_LIST";
export const SET_SEARCH_EMPLOYEE_VACATION = "SET_SEARCH_EMPLOYEE_VACATION";



//Rh
export const SET_SELECTED_REGISTER_RH = "SET_SELECTED_REGISTER_RH";
export const SET_SELECTED_REGISTER_ID = "SET_SELECTED_REGISTER_ID";
export const FETCH_EMPLOYEE_LIST = "FETCH_EMPLOYEE_LIST";
export const FETCH_DEPARTMENT_LIST = "FETCH_DEPARTMENT_LIST";
export const FETCH_EMPLOYEE_FOR_REGISTER_LIST =
  "FETCH_EMPLOYEE_FOR_REGISTER_LIST";
export const SET_REGISTERS = "SET_REGISTERS";
export const ADD_SMALLBOX_REGISTER = "ADD_SMALLBOX_REGISTER";
export const INITIALIZE_REGISTER = "INITIALIZE_REGISTER";
export const SET_REGISTERS_DETAILS = "SET_REGISTERS_DETAILS";
export const SAVE_REGISTER = "SAVE_REGISTER";
export const FETCH_REGISTERS = "FETCH_REGISTERS";
export const SELECTED_REGISTER_DETAIL = "SELECTED_REGISTER_DETAIL";
export const CLEAR_NEW_REGISTER = "CLEAR_NEW_REGISTER";
export const SET_SELECTED_REGISTER = "SET_SELECTED_REGISTER";
export const SET_SELECTED_REGISTERS_DETAILS = "SET_SELECTED_REGISTERS_DETAILS";

//Perceptions
export const SHOW_NEW_PERCEPTION_OVERLAY = "SHOW_NEW_PERCEPTION_OVERLAY";
export const SET_PERCEPTION_TYPE_LIST = "SET_PERCEPTION_TYPE_LIST";
export const SET_EMPLOYEE_PERCEPTIONS_LIST = "SET_EMPLOYEE_PERCEPTIONS_LIST";

//Deductions
export const SHOW_NEW_DEDUCTION_OVERLAY = "SHOW_NEW_DEDUCTION_OVERLAY";
export const SET_DEDUCTION_TYPE_LIST = "SET_DEDUCTION_TYPE_LIST";
export const SET_EMPLOYEE_DEDUCTIONS_LIST = "SET_EMPLOYEE_DEDUCTIONS_LIST";

//Payroll
export const SET_PAYROLL_LIST = "SET_PAYROLL_LIST";
export const SET_SELECTED_PAYROLL = "SET_SELECTED_PAYROLL";
export const SET_PAYROLL_DETAILS = "SET_PAYROLL_DETAILS";

