//SITEMAFC
export const SET_SELECTED_REGISTER_RH = "SET_SELECTED_REGISTER_RH";
export const SET_SEARCH_REGISTER_RH = "SET_SEARCH_REGISTER_RH";
export const SHOW_NEW_EMPLOYEE_OVERLAY = "SHOW_NEW_EMPLOYEE_OVERLAY";

//Auth
export const SIGNIN = "SIGNIN";


//Rh
export const FETCH_EMPLOYEE_LIST = "FETCH_EMPLOYEE_LIST";
export const FETCH_DEPARTMENT_LIST = "FETCH_DEPARTMENT_LIST";

